# Generated by Django 5.0.4 on 2024-07-04 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_record_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='user_record_id',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
