# Generated by Django 5.0.4 on 2024-07-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_record_user_record_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='record',
            name='creator',
        ),
        migrations.AlterField(
            model_name='record',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='record',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='province',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='user_record_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
