# Generated by Django 5.0.4 on 2024-07-04 03:54

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_remove_record_creation_date_remove_record_creator_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='user_record_id',
        ),
        migrations.AddField(
            model_name='record',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='record',
            name='creator',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='record',
            name='address',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='record',
            name='city',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='record',
            name='country',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='record',
            name='email',
            field=models.EmailField(max_length=80),
        ),
        migrations.AlterField(
            model_name='record',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='province',
            field=models.CharField(max_length=80),
        ),
    ]
