# Generated by Django 5.0.4 on 2024-07-06 01:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_remove_record_user_record_id_record_creation_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='user_record_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='record',
            constraint=models.UniqueConstraint(fields=('creator', 'user_record_id'), name='unique_user_record'),
        ),
    ]
