# Generated by Django 5.0.4 on 2024-07-06 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_record_user_record_id_record_unique_user_record'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='record',
            name='unique_user_record',
        ),
        migrations.RemoveField(
            model_name='record',
            name='user_record_id',
        ),
    ]
